

default: princ_eleve

all: princ_eleve

debug:
	gcc -Wall princ2.c eleves.c -g -o princ_elev.o

princ_eleve:
	gcc -Wall princ2.c eleves.c -o princ_elev.o

clean:
	rm -f *.o

debug1:
	gcc -g gdb_1.c -o gdb_1.o